<a href="https://colab.research.google.com/github/GbrlOl/python-course/blob/main/module_course_by_GabrielOlmos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Curso de Módulos

El siguiente colab contiene los fundamentos para aprender los frameworks más utilizados en python y para el curso.

# Tabla de Contenidos

1. Numpy

# Numpy

| [Documentación Oficial de NumPy](https://numpy.org) |

NumPy en google colab ya viene instalado, por lo cual, no hay que realizar un `!pip install numpy`

In [ ]:
!pip show numpy

Name: numpy
Version: 1.25.2
Summary: Fundamental package for array computing in Python
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD-3-Clause
Location: /usr/local/lib/python3.10/dist-packages
Requires: 
Required-by: albumentations, altair, arviz, astropy, autograd, blis, bokeh, bqplot, chex, cmdstanpy, contourpy, cufflinks, cupy-cuda12x, cvxpy, datascience, db-dtypes, dopamine-rl, ecos, flax, folium, geemap, gensim, gym, h5py, holoviews, hyperopt, ibis-framework, imageio, imbalanced-learn, imgaug, jax, jaxlib, librosa, lida, lightgbm, matplotlib, matplotlib-venn, missingno, mizani, ml-dtypes, mlxtend, moviepy, music21, nibabel, numba, numexpr, opencv-contrib-python, opencv-python, opencv-python-headless, opt-einsum, optax, orbax-checkpoint, osqp, pandas, pandas-gbq, patsy, plotnine, prophet, pyarrow, pycocotools, pyerfa, pymc, pytensor, python-louvain, PyWavelets, qdldl, qudida, scikit-image, scikit-learn, scipy, scs, seaborn, shapely, s

In [2]:
import numpy as np

## Arrays

| [Arrays numpy](https://numpy.org/doc/stable/reference/generated/numpy.array.html) |

In [3]:
# Creación de un array unidimensional

arr1 = np.array([1, 2, 3, 4, 5])

In [4]:
arr1

array([1, 2, 3, 4, 5])

In [5]:
# Podemos preguntar la longitud, forma, tipo de dato, entre otros.

print(arr1.size)
print(arr1.shape)
print(arr1.dtype)

5
(5,)
int64


In [7]:
# Podemos crear un array bidimensional (matriz)

matriz = [
    [9,8,9],
    [4,8,4],
    [1,2,3]
]

# Creamos nuestra matriz numpy y podemos especificar el tipo de datos que queramos
arr2 = np.array(matriz, dtype=np.float32)

print("Longitud de la matriz o cantidad de elementos totales: ", arr2.size)
print("Forma de la matriz: ", arr2.shape)
print("Tipo de dato de la matriz: ", arr2.dtype)

Longitud de la matriz o cantidad de elementos totales:  9
Forma de la matriz:  (3, 3)
Tipo de dato de la matriz:  float32


In [11]:
# Podemos utilizar métodos para crear vectores, matrices con ceros, unos o valores aleatorios

vect1 = np.zeros(6)
vect1

array([0., 0., 0., 0., 0., 0.])

In [12]:
vect2 = np.zeros((3,6))
vect2

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [13]:
vect1 = np.ones(5)
vect1

array([1., 1., 1., 1., 1.])

In [15]:
vect2 = np.ones((5,5))
vect2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
# Podemos crear la matriz identidad
vect = np.eye(3,3)
vect

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Podemos sumar, restar, multiplicar, dividir arrays, es decir, todas las operaciones aritméticas

In [19]:
arr_1 = np.array([3,2,1,3])

arr_2 = np.array([1,1,1,1])

print("Suma: ", arr_1 + arr_2)
print("Resta: ", arr_1 - arr_2)
print("Multiplicación: ", arr_1 * arr_2)
print("División: ", arr_1 / arr_2)

Suma:  [4 3 2 4]
Resta:  [2 1 0 2]
Multiplicación:  [3 2 1 3]
División:  [3. 2. 1. 3.]


Podemos crear un vector que contenga `n elementos`.

In [21]:
# Creamos un vector que vaya del 1 al 10 con 10 elementos

vector = np.linspace(1,10,10)
vector

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

Podemos realizar un reshape a ese vector, es decir, podemos convertir el vector en una matriz.

In [25]:
new_vector = vector.reshape(5,2)

print("Vector: ", vector)
print("Matriz: \n", new_vector)

Vector:  [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
Matriz: 
 [[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]
 [ 7.  8.]
 [ 9. 10.]]


AL igual con las listas de python, con numpy podemos realizar slicing.

In [27]:
my_array = np.linspace(1,20,20)
my_array

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20.])

In [28]:
my_array[0]

1.0

In [29]:
my_array[-1]

20.0

In [30]:
my_array[::2]

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.])

In [31]:
my_array[1::2]

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [32]:
my_array[15:]

array([16., 17., 18., 19., 20.])

In [34]:
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distribut

In [42]:
my_matrix = np.random.randint(5, size=(2, 4))
my_matrix

array([[0, 1, 1, 0],
       [2, 4, 1, 4]])

In [44]:
# Podemos acceder a cualquier elemento de la matriz, en este caso al último elemento

my_matrix[-1,-1]

4